#!/usr/bin/env python

import fileinput
from os import environ
from pprint import pprint


for k,v in environ.iteritems():
    print k,'=',v

for line in fileinput.input():
    old_ref, new_ref, branch = line.split(' ')
    print old_ref, new_ref, branch